# Generated by Django 3.2.13 on 2022-06-09 09:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=core.models.upload_to, verbose_name='Image'),
        ),
    ]
