# Generated by Django 3.2.13 on 2022-06-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
