# Generated by Django 3.2.13 on 2022-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220607_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user is already registered with this email address'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
